version: "3.9"
services:
  apiserver:
    container_name: table_apiserver
    networks:
      - table
    build: ./backend
    restart: unless-stopped
    depends_on:
      - mongo
      - elasticsearch
    environment:
      MONGO_HOST: mongo
      ELASTICSEARCH_HOSTS: '["elasticsearch:9200"]'
    ports:
    - "8080:80"

  webserver:
    container_name: table_webserver
    networks:
      - table
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - apiserver
    ports:
    - "8000:80"

  nginx:
    container_name: table_nginx
    networks:
      - table
    build: ./
    restart: unless-stopped
    depends_on:
      - apiserver
      - webserver
    ports:
      - "80:80"


networks:
  table:
    driver: bridge